name: Test action
on:
  push:
jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: './.github/sendinblue/mockbin-action'
        with:
          command: kubectl

      - uses: './.github/sendinblue/mockbin-action'
        with:
          command: kustomize

      - name: Act
        uses: './'
        with:
          resource-directory: './'
          image: my-image
#          secrets-name: my-secret-name
#          secrets: |
#            foo=bar

      - uses: './.github/sendinblue/mockbin-action'
        with:
          command: kustomize
          assert-call-index: 0
          assert-args: '["edit", "set", "image", "my-image"]'

      - uses: './.github/sendinblue/mockbin-action'
        with:
          command: kustomize
          assert-call-index: 1
          assert-args: '["bild"]'

      - uses: './.github/sendinblue/mockbin-action'
        with:
          command: kubectl
          assert-call-index: 0
          assert-args: '["apply", "--dry-run=\"none\"", "--filename", "-"]'
