name: 'Mockbin Action'
description: 'Tool for testing actions by mocking binaries'
inputs:
  command:
    description: 'Command to mock'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure image, secrets, and deploy image
      env:
        MOCKBINPATH: ${{ github.workspace }}/.mockbin
        MOCKCOMMAND: ${{ inputs.command }}
      run: |
        if [[ ! -d "$MOCKBINPATH" ]]; then
          mkdir -p "$MOCKBINPATH"
          NODEJS=$(which node)
          PATH="$MOCKBINPATH:$PATH"
          echo "Extending PATH: $PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "MOCKBINPATH=$MOCKBINPATH" >> $GITHUB_ENV
        fi

        # Create executable mock
        echo "#!${NODEJS}" > "$MOCKBINPATH/$MOCKCOMMAND"
        cat "${{ github.action_path }}/assets/mockbin.js" >> "$MOCKBINPATH/$MOCKCOMMAND"
        chmod +x "$MOCKBINPATH/$MOCKCOMMAND"

      shell: bash
